export const PT_BR = {
  labels: {
    email: 'E-mail',
    password: 'Senha',
    name: 'Nome',
    accessLevel: 'Nível de acesso',
    status: 'Status',
    processId: 'ID Processo',
    responsible: 'Responsável',
    coordination: 'Coordenação',
    modality: 'Modalidade',
    priority: 'Prioridade',
  },
  auth: {
    signIn: 'Entrar',
    signingIn: 'Entrando...',
    invalidCredentials: 'E-mail ou senha inválidos.',
    forgotPassword: 'Esqueci minha senha',
    noAccount: 'Não tem conta?',
  },
  roles: {
    admin: 'Acesso total ao sistema',
    gestor: 'Gerenciar processos e responsáveis',
    consultor: 'Criar, visualizar, editar e excluir processos',
    visualizador: 'Apenas leitura',
  },
  aging: {
    concluded: 'Concluído',
    overdue: (d: number) => `Atrasado ${Math.abs(d)}d`,
    dueIn: (d: number) => `Vence em ${d}d`,
    onTime: (d: number) => `No Prazo (${d}d)`,
    overdueSimple: 'Atrasado',
    na: 'Não aplicável',
    noDeadline: 'Sem prazo',
  },
  filters: {
    today: 'Hoje',
    days7: '7 dias',
    days30: '30 dias',
    year: 'Ano',
    allStatus: 'Todos os status',
    reset: 'Resetar',
  },
  contrato: {
    numero: 'Nº Contrato',
    contratada: 'Contratada',
    cnpj: 'CNPJ',
    objeto: 'Objeto',
    valorInicial: 'Valor Inicial',
    valorAtual: 'Valor Atual',
    valorExecutado: 'Valor Executado',
    valorPago: 'Valor Pago',
    saldo: 'Saldo',
    dataAssinatura: 'Data de Assinatura',
    dataPublicacao: 'Data de Publicação',
    dataInicioVigencia: 'Início da Vigência',
    dataFimVigencia: 'Fim da Vigência',
    dataLimiteRenovacao: 'Data Limite para Renovação',
    dataEncerramento: 'Data de Encerramento',
    gestor: 'Gestor do Contrato',
    fiscalTecnico: 'Fiscal Técnico',
    fiscalAdministrativo: 'Fiscal Administrativo',
    diasRestantes: 'Dias Restantes',
    contratoEmergencial: 'Contrato Emergencial',
    permiteAditivo: 'Permite Aditivo',
    permiteRenovacao: 'Permite Renovação',
    temGarantia: 'Tem Garantia',
    observacoes: 'Observações',
  },
  googleDrive: 'Pasta/arquivo no Google Drive',
  loading: {
    checkingSession: 'Verificando sessão...',
    loadingData: 'Carregando dados...',
  },
}
